[package]
name = "wasmer/edge-on-cdn-tutorial"
version = "0.1.8"
description = "wasmer/edge-on-cdn-tutorial website"

[dependencies]
"wasmer/static-web-server" = "^1"

[fs]
"/app" = "."

[[command]]
name = "script"
module = "wasmer/static-web-server:webserver"
runner = "https://webc.org/runner/wasi"

[command.annotations.wasi]
main-args = ["-w", "/app/config.toml"]
